import { Layout } from "./components/Layout/Layout";
import { Roboto } from "next/font/google";
import "./globals.css";
import "react-datepicker/dist/react-datepicker.css";
import { ReactNode } from "react";

const roboto = Roboto({
  style: ["normal"],
  subsets: ["latin"],
  weight: "300",
});
export const metadata = {
  title: "Weather Center",
  description: "The weather application",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}

/*
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
  */
